### ISSUE TITLE
Frozon spec.metadata["msys2_mingw_dependencies"] value doesn't work

### ISSUE THREAD

**Issue by kou** [MSP-Greg/ruby-loco#4]
Because https://github.com/MSP-Greg/ruby-loco/blob/master/patches/__operating_system.rb.patch#L21 uses `String#sub!`. Can we use `deps = deps.sub(d, '')` here?

An error output: https://github.com/ruby/fiddle/runs/1408885075?check_suite_focus=true

**Comment by MSP-Greg** [comment]
@kou

Sorry about that.  Fixed, it will take ~ 45-50 minutes for a new build.

I added it a long time ago, maybe I can remove it, but it helped with testing against a custom package.

For instance, testing against OpenSSL 3.0 when the 'proper' MSYS2 package is 1.1.1.  I know Lars made some changes recently...

**Comment by kou** [comment]
Wow! Thanks for your quick fix!
I've confirmed that this has been fixed.

**Comment by MSP-Greg** [comment]
And thanks for your quick check.  I was just updating my fiddle repo and about to run CI...
