### ISSUE TITLE
Patch to operating_system.rb is no longer necessary

### ISSUE THREAD

**Issue by larskanis** [MSP-Greg/ruby-loco#5]
Hi @MSP-Greg ! I noticed you still have this patch in place: https://github.com/MSP-Greg/ruby-loco/blob/1e6c9ecbb648dbabb01f112ebda3f4f2e1a62c11/patches/__operating_system.rb.patch

but I think it's no longer necessary since this commit: https://github.com/oneclick/rubyinstaller2/commit/b57236b24b702eced2bb79d84930f642883dca92#diff-7ed5283cfd0f0f534710a4f2b007dcbec407909e4e70b7adaeb897ae9bb88ea2

**Comment by MSP-Greg** [comment]
@larskanis

Ok, for you, removed.  I saw your change, meant to double check it with a locally installed package (like OpenSSL 3.0.0) to see if it was left as is.

FYI, haven't pushed the change yet, as Ruby master is failing Actions CI. Odd thing is that I still build ruby-loco on AppVeyor, and it's passing...
